import { BadRequestError } from "../Errors/customErrors";
import * as getContactService from './getContacts.service';

export const getContact = async (req, res, next) => {
    try {



    } catch (err) {
        next(err)
    }
}